### PR TITLE
Development

### PR DESCRIPTION
**Pull request by snehalteli**
# Create review category component.

Description
1. Did changes in Review Category Element in design type
2. Added Review Category Component 
   a) Added Design Type to component

### CODE REVIEW

**Review by Niphy-Anto — COMMENTED** [review]
RdsButtonModule should be addeed in badge.stories.ts,

**Review by Niphy-Anto — COMMENTED** [review]
Not ready to commit

**Comment by Niphy-Anto** [comment]
RdsSizeModule import in not correct in app,module.ts of rds-components, RdsButtonModule should be there in Badge.stories.ts,
Remove the newly added section from angular.json

**Review by Niphy-Anto — COMMENTED** [review]
Code verified and ready to commit

**Review by alok-nakhate — APPROVED** [review]
Changes are reviewed and approved

**Pull request merged**
